package com.wealoha.thrift;

import org.apache.thrift.TServiceClient;
import org.apache.thrift.protocol.TBinaryProtocol;
import org.apache.thrift.protocol.TProtocol;
import org.apache.thrift.transport.TTransport;

/**
 * All IFace(subclass of TServiceClient) were generated by thrift.
 * We don't know their types. <br/>
 * Since they all extends super class TServiceClient,
 * construct a new Client need only just one line.<br/>
 * 
 * @author javamonk
 * @createTime 2014年11月22日 下午2:49:53
 */
public interface ThriftClientFactory<T extends TServiceClient> {

    /**
     * return a new client using protocol<br/>
     * 
     * <code>
     * <pre>
     *     public TServiceClient makeClient(TProtocol protocol) {
     *         return new Client(protocol);
     *     }
     * </pre>
     * </code>
     * 
     * @param protocol
     * @return
     */
    T createClient(TProtocol protocol);

}
